### ISSUE TITLE
Please add extraVol example for scheduler and worker pods in docs.

### ISSUE THREAD

**Issue by deepaksharma23** [astronomer/docs#1221]
Please add extraVol example for scheduler and worker pods in docs.

- Please add in docs as an example in platform setup or management. 

```
astronomer:
  houston:
    config:
      deployments:
        helm:
          scheduler:
            extraVolumes: []
            extraVolumeMounts: []
          workers:
            extraVolumes: []
            extraVolumeMounts: []

```

Customers is asking for examples regarding these queries like how to make data persistent for workers or mounting extraVol in the scheduler or webserver.

We can avoid ticket counts and make our documents more useful for the software customers. like

https://astronomer.zendesk.com/agent/tickets/8413
