### ISSUE TITLE
Private Installation Section

### ISSUE THREAD

**Issue by jwitz** [astronomer/docs#134]
@vparekh94 commented on [Mon May 13 2019](https://github.com/astronomer/issues/issues/166)

We should have a section under "Customizing the install" that goes over what has to happen to deploy in a cluster without internet access.

There should be one section per cloud that goes over:

- [ ] Cloud specific info
- [ ] Move all images to internal repo
- [ ] Modify Commander image
- [ ] Turn off email confirmation
- [ ] DNS

---

@vparekh94 commented on [Mon Jun 03 2019](https://github.com/astronomer/issues/issues/166#issuecomment-498309641)

Related to:
https://github.com/astronomer/docs/issues/97
astronomer/astronomer#310
https://github.com/astronomer/houston-api/issues/64

---

@petedejoy commented on [Tue Nov 12 2019](https://github.com/astronomer/issues/issues/166#issuecomment-552903649)

+1-ing the need for this- I could use something like this for a couple of prospects at the moment. I'd also love to learn about it myself.

---

@paolaperaza commented on [Wed Apr 15 2020](https://github.com/astronomer/issues/issues/166#issuecomment-614256867)

@vparekh94 Reviewing open docs issues and wanted to bump this one as an FYI/reminder that it exists.

Don't think any action is needed on it at the moment, but if we push features to the platform in v0.14 or v0.15 that'd allow customers to run Enterprise in an air-gapped environment it'd be great to push out this doc as well.

**Comment by rbankston** [comment]
Ran into an issue with a private air gapped environment where egress was disabled. The auth section explicitly needs

```
auth:
        github:
          enabled: false # Lets users authenticate with Github
        local:
          enabled: true # Disables logging in with just a username and password
        openidConnect:
          google:
            enabled: false # Lets users authenticate with Google
```

or github and google endpoints need to be allowed egress. If that isn't set the login page never shows up for local auth.
