### ISSUE TITLE
Update Install Python Packages from Private Sources

### ISSUE THREAD

**Issue by kwcanuck** [astronomer/docs#1824]
@jedcunningham recommended the following changes to the topic to [Install Python packages from private sources](https://docs.astronomer.io/astro/develop-project?tab=github#install-python-packages-from-private-sources):

- Use double quotes vs single quotes when adding to PATH

- Don’t keyscan on the fly, hard code the github key, better to point folks [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints). keyscan comment is okay as well for other services.

- Need to move the USER root up - @pohek321 to confirm.

@jedcunningham also made the following suggestions:

- Are those labels really necessary? Just extra noise imo.

- Instead of using base and reimplementing worse versions of the [onbuild commands](https://github.com/astronomer/astro-runtime/blob/main/image/Dockerfile.onbuild), why not use the onbuild image and just install the 1 extra private package with pip at the end? Less fragile to upstream image changes too.

These changes originated with this [Slack conversation](https://astronomer.slack.com/archives/C01N2DM2ZS8/p1675196726836089).

**Comment by pohek321** [comment]
@jedcunningham & @kwcanuck I heard back from the customer, and this is what they had to do to get it working:

*Dockerfile*
```Dockerfile
FROM quay.io/astronomer/astro-runtime:7.2.0-base AS stage1

LABEL maintainer="Astronomer <[humans@astronomer.io](mailto:humans@astronomer.io)>"
ARG BUILD_NUMBER=-1
LABEL io.astronomer.docker=true
LABEL io.astronomer.docker.build.number=$BUILD_NUMBER
LABEL io.astronomer.docker.airflow.onbuild=true

# Install OS-Level packages
USER root
COPY packages.txt .
RUN apt-get update && cat packages.txt | xargs apt-get install -y

FROM stage1 AS stage2
RUN apt-get -y install git python3 openssh-client

RUN mkdir -v -p -m 700 ~/.ssh
RUN ssh-keyscan [github.com](http://github.com/) >> ~/.ssh/known_hosts
RUN chmod 644 ~/.ssh/known_hosts
# Install Python packages
COPY requirements.txt .
RUN --mount=type=ssh,id=github,mode=0666 pip install --no-cache-dir -q -r requirements.txt

FROM stage1 AS stage3
# Copy requirements directory
COPY --from=stage2 /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=stage2 /usr/local/bin /home/astro/.local/bin
ENV PATH="/home/astro/.local/bin:$PATH"

COPY . .

USER astro
```

*requirements.txt*
```
git+ssh://git@github.com/org/repo.git
```

*gh_deploy.yaml*
```yaml
test-push:
if: github.ref == 'refs/heads/test' #&& github.event.pull_request.merged == true
env:
## Sets Deployment API key credentials as environment variables
ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_TEST_KEY_ID }}
ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_TEST_KEY_SECRET }}
runs-on: ubuntu-latest
steps:
- name: checkout repo
uses: actions/[checkout@v2.3.4](mailto:checkout@v2.3.4)
- name: Create image tag
id: image_tag
run: echo ::set-output name=image_tag::astro-$(date +%Y%m%d%H%M%S)
- name: Create SSH Socket
uses: webfactory/[ssh-agent@v0.7.0](mailto:ssh-agent@v0.7.0)
with:
ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
- name: Test SSH Connection - Should print hello message.
run: ssh [git@github.com](mailto:git@github.com) || true
- name: Build image
uses: docker/build-push-action@v2
with:
tags: ${{ steps.image_tag.outputs.image_tag }}
load: true
ssh: |
github=${{ env.SSH_AUTH_SOCK }}
- name: Deploy to Astro
run: |
curl -sSL [install.astronomer.io](http://install.astronomer.io/) | sudo bash -s
astro deploy --image-name ${{ steps.image_tag.outputs.image_tag }} ${{ secrets.ASTRONOMER_TEST_DEPLOYMENT_ID }}
```
