### ISSUE TITLE
Lack of dag only deploy documentation for gitlab

### ISSUE THREAD

**Issue by frankcash** [astronomer/docs#2134]
**Affected Document:**

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)
- [x] Documentation lacking (low)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
This is a single branch example, would be easy to add secondary information support multiple branches

```yaml
publish-dags:
  stage: publish
  image: docker:latest
  services:
   - docker:dind
  variables:
    ASTRONOMER_KEY_ID: ${ASTRONOMER_KEY_ID}
    ASTRONOMER_KEY_SECRET: ${ASTRONOMER_KEY_SECRET}
    DAG_FOLDER: "/dags"
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add bash
    - apk add jq
  script:
    - (curl -sSL install.astronomer.io | bash -s)
    - files=$(git diff --name-only HEAD^..HEAD)
    - dags_only=1
    - for file in $files; do
    -  if [[ $file != "$DAG_FOLDER"* ]]; then
    -    echo "$file is not a dag, triggering a full image build"
    -    dags_only=0
    -    break
    -  fi
    - done
    - if [ $dags_only == 1 ]
    - then
    -   astro deploy --dags
    - fi
    - if [ $dags_only == 0 ]
    - then
    -   astro deploy -f
    - fi
  only:
    - main

```

https://docs.astronomer.io/astro/ci-cd#gitlab

**Additional Notes:**
