### ISSUE TITLE
Update documentation to comment on internal eks clusters

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#263]
**Affected Document:**

https://www.astronomer.io/docs/enterprise/v0.23/install/aws/install-aws-standard
  
**Severity:**

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [x] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [ ] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
The helm values given could benefit from adding an extra line to the default of false so people are aware it exists

```
nginx:
  # IP address the nginx ingress should bind to
  loadBalancerIP: ~
```
becomes

```
nginx:
  # IP address the nginx ingress should bind to
  loadBalancerIP: ~
  #  Set to 'true' when deploying to a private EKS cluster
  privateLoadBalancer: false 
```

**Additional Notes:**
