### ISSUE TITLE
Docker Compose Override doc showing old version of docker compose config

### ISSUE THREAD

**Issue by dintorf** [astronomer/docs#296]
**Affected Document:**

Customize Images in the Docker Compose Override section is showing version `2.0` for the override and the default code is using `3.1`. 

https://www.astronomer.io/docs/cloud/stable/develop/customize-image#docker-compose-override

![image](https://user-images.githubusercontent.com/7852928/149563067-27de2747-9348-4495-848b-fc00cf49113e.png)

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [x] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

Change the docker compose override doc to reflect the new `3.1` version of the config.

```yaml
version: "3.1"
services:
  scheduler:
    volumes:
      - /home/astronomer_project/custom_dependencies:/usr/local/airflow/custom_dependencies:ro
```

**Additional Notes:**
