### ISSUE TITLE
Typo in example helm values for resourceProvisioningStrategy

### ISSUE THREAD

**Issue by danielhoherd** [astronomer/docs#3414]
### Issue Type

Inaccurate, misleading, or out-of-date information

### Links to Affected Docs

https://docs.astronomer.io/software/customize-resource-usage#disable-astronomer-units-aus-from-deployment-resource-configurations

### The Issue or Context

the example shows:
```
astronomer:
  houston:
    deployments:
      resourceProvisioningStrategy:
        astroUnitsEnabled: false
```
but the values that are needed are:
```
$ helm get values --all -n development astrodev -o json | gron | grep resourceProvisioning | gron -u | yq -y .
astronomer:
  houston:
    config:
      deployments:
        resourceProvisioningStrategy:
          astroUnitsEnabled: false
```
N.b.: that is the python version of yq, not the golang one, not the rust one. `pipx install yq`

### Fix or Proposed Change

```
astronomer:
  houston:
    config:
      deployments:
        resourceProvisioningStrategy:
          astroUnitsEnabled: false
```

### Additional Notes

slack thread: <https://astronomer.slack.com/archives/CEPE4K68P/p1708007258645619>
