### ISSUE TITLE
Missing | in code example

### ISSUE THREAD

**Issue by lzdanski** [astronomer/docs#3554]
### Issue Type

Typo or broken link

### Links to Affected Docs

https://docs.astronomer.io/software/install-airgapped#configuring-a-custom-updates-json-url

### The Issue or Context

Got a report for malformed yaml in a code example that needs a `|` added. 

### Fix or Proposed Change

Replace code example with 

```yaml
astronomer:
  houston:
    updateCheck:
      enabled: false
    updateAirflowCheck:
      url: http://astronomer-releases.astronomer-airflow-poc1.svc.cluster.local/astronomer-certified
    updateRuntimeCheck:
      url: http://astronomer-releases.astronomer-airflow-poc1.svc.cluster.local/astronomer-runtime
    config:
      deployments:
        helm:
          airflow:
            extraEnv: |
              - name: AIRFLOW__ASTRONOMER__UPDATE_URL
                value: http://astronomer-releases.astronomer-airflow-poc1.svc.cluster.local/astronomer-runtime
```

### Additional Notes

https://astronomer.slack.com/archives/C015V2JFKT5/p1710968911975989
