### ISSUE TITLE
Alertmanger Configuration not working

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#387]
https://www.astronomer.io/docs/enterprise/v0.25/monitor/platform-alerts
  
**Severity:**

- [ ] Critical: This document has incorrect or missing information. Add the `error/critical` label to this issue.
- [ ] FYI: The document is misleading or could benefit from additional context or guidance. Add the `error/FYI` label to this issue.
- [x] Typo: Add the `error/typo` label to this issue.
  
**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
```
alertmanager:
  receivers:
    # Configs for platform alerts
    platform: 

    platformCritical: 
        slack_configs:
        - api_url: https://hooks.slack.com/services/T02J89GPR/BDBSG6L1W/4Vm7zo542XYgvv3
          channel: '#astronomer_platform_alerts'
          text: |-
            {{ range .Alerts }}{{ .Annotations.description }}
            {{ end }}
          title: '{{ .CommonAnnotations.summary }}'
```

Without removing the {} I wasn't able to get helm to parse the values listed in there. The -name also causes alertmanager to fail to start with an error. 

**Additional Notes:**
If possible it would be nice to give more information with more examples of a configuration similar to our production cloud would look like for enterprise customers.
