### ISSUE TITLE
Astro Cloud - GitHub Actions CI/CD Example incorrectly formatted

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#483]
**Affected Document:**

The formatting when copying/pasting from our github actions example does not work out-of-the-box because of indentation issues:
https://docs.astronomer.io/astro/ci-cd/#github-actions

**Problem Type (Priority):**

- [X] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

Several changes outlined below:
1. Remove reference to `organization-id`, it is no longer included in the script
2. Update script to match the below example with proper indentation
3. Replace `<deployment-id>` in the script with an actual GitHub variable (same way the KEY_ID and KEY_SECRET are set up)

Here is a fixed version of the script that works:

```
name: Astronomer CI - Deploy Code

on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
  ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        brew install astronomer/cloud/astrocloud
        astrocloud deploy ${{ secrets.DEPLOYMENT_ID }}
```

**Additional Notes:**

**Note:** I also changed the last line `astrocloud deploy <deployment-id>` to be: `astrocloud deploy ${{ secrets.DEPLOYMENT_ID }}`
As a result, I think the instructions should be updated slightly as well:
**Before:**
```
1. Set the following as [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository):
ASTRONOMER_KEY_ID = <your-key-id>
ASTRONOMER_KEY_SECRET = <your-key-secret>

2. Add the following to a new file in .github/workflows, making sure to replace <organization-id> and <deployment-id> with the values for your Deployment:
```

**After**: (this also removes reference to organization-id which is no longer in the script)
```
1. Set the following as [GitHub secrets](https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository):
ASTRONOMER_KEY_ID = <your-key-id>
ASTRONOMER_KEY_SECRET = <your-key-secret>
DEPLOYMENT_ID = <your-astro-deployment-id>

2. Add the following to a new file in .github/workflows, for example `cicd.yaml`:
```
