### ISSUE TITLE
GitHub Actions - Multi-branch CI/CD 

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#525]
**Affected Document:**

 Astro CI/CD: https://docs.astronomer.io/astro/ci-cd#cicd-templates

**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

Our existing software docs provides an example of a multi-branch pipeline and mentions the ability to add specific trigger rules, branch protection rules, etc - but this info and suggestion is missing from our Astro docs - and creating a multi branch pipeline on Astro is not as straightforward as Software due to the use of Astro CLI to deploy

I put together a ci/cd yaml for github actions that can be used for dev/prod environments to match the flow we suggest in this diagram in our [Software docs](https://docs.astronomer.io/software/ci-cd#example-cicd-workflow):
<img width="839" alt="image" src="https://user-images.githubusercontent.com/15913202/159057223-0a28a4ea-920b-43af-a098-284747dbd9a8.png">

```
name: Astronomer CI - Deploy Code

on:
  push:
    branches: [dev]
  pull_request:
    types:
      - closed
    branches: [main]

jobs:
  dev-push:
    if: github.ref == 'refs/heads/dev'
    env:
      ## Sets DEV Deployment API key credentials as environment variables
      ASTRONOMER_KEY_ID: ${{ secrets.DEV_ASTRONOMER_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.DEV_ASTRONOMER_KEY_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        brew install astronomer/cloud/astrocloud
        astrocloud deploy ${{ secrets.DEV_DEPLOYMENT_ID }}
  prod-push:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    env:
      ## Sets PROD Deployment API key credentials as environment variables
      ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        brew install astronomer/cloud/astrocloud
        astrocloud deploy ${{ secrets.DEPLOYMENT_ID }}
```

**Additional Notes:**
The flow of this action:
- User has a `main` and a `dev` branch
- User pulls updates into `main` and then brings those changes into `dev`
- User develops dags/makes changes and is ready to test in `dev` environment ---> push to their repo from their `dev` branch
- This triggers a dev build & deploy immediately upon the user pushing changes to the repo (PR is not required at this point)
- User makes sure changes work as expected in their `dev` deployment, and is ready to merge into `main`
- User creates a pull request to merge `dev` into `main`, and has another member of the team review the code
- Upon the PR merge, the `prod` deploy will occur
- Note, users must create two sets of Env Vars in their github secrets (2 deployment IDs, and 2 sets of Key/Secret API pairs)
