### ISSUE TITLE
Add Info on Testing KPO Locally

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/docs#603]
### Problem

Today, @ReadytoRocc was working with a prospect who needs to test the KubernetesPodOperator locally and found that our existing KPO doc on the subject doesn't have the detailed information needed to actually complete this workflow according to best practices.

His ask:

> Hey Docs team, I have a prospect who was interested in using KPO locally with Docker Desktop and our CLI. I augmented our [guide](https://docs.astronomer.io/astro/test-and-troubleshoot-locally/#test-the-kubernetespodoperator-locally) with these instructions. I think they could be an addition to our docs. Any feedback would be appreciated, thanks!

**Doc:** https://docs.astronomer.io/astro/kubernetespodoperator
**Reviewer:** @ReadytoRocc 

### Action Item
As part of closing out this GitHub issue, we need to:

- Create a new "Test KPO Locally" Doc in Astro that [mirrors the one that exists for Software](https://docs.astronomer.io/software/kubepodoperator-local)
- Add the steps that Rocco outlined
- Add those steps to the Software version too

### Content Needed
We should add the following to the doc:

> In addition to our [guide](https://docs.astronomer.io/astro/test-and-troubleshoot-locally/#test-the-kubernetespodoperator-locally) for setting up KPO to run locally with our CLI, please see these additional steps:
>    - When creating the include/.kube/config file for your astro project, the cluster name should be searchable as docker-desktop in your local $HOME/.kube/config file.
>    - Below I have shared an example config file. Please fill in CERT_AUTHORITY_DATA, CERT_CLIENT_DATA, and CERT_KEY_DATA with your own values.
>    - Note that no other cluster contexts should be included in your include/.kube/config file.
>    -  Please add `.kube` in your `.dockerignore` so that the config file is not included in your image build.
>    - If you have set your project up as a git repo, please also include` .kube` in your `.gitignore` file so that the config file is not tracked by version control.

Example `include/.kube/config`

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: CERT_AUTHORITY_DATA
    server: https://kubernetes.docker.internal:6443/
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: CERT_CLIENT_DATA
    client-key-data: CERT_KEY_DATA
```
