### ISSUE TITLE
Alertmanager example config Indentation issue

### ISSUE THREAD

**Issue by rbankston** [astronomer/docs#606]
**Affected Document:**

**Problem Type (Priority):**

- [x] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [ ] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**

```
alertmanager:
  receivers:
    # Configs for platform alerts
    platform:
      email_configs:
      - smarthost: smtp.sendgrid.net:587
        from: <your-astronomer-alert-email@company.com>
        to: <your-email@company.com>
        auth_username: apikey
        auth_password: SG.myapikey1234567891234abcdef_bKY
        send_resolved: true
    platformCritical:
      slack_configs:
      - api_url: https://hooks.slack.com/services/abc12345/abcXYZ/xyz67890
        channel: '#<your-slack-channel-name>'
        text: |-
          {{ range .Alerts }}{{ .Annotations.description }}
          {{ end }}
        title: '{{ .CommonAnnotations.summary }}'
```

to

```
alertmanager:
  receivers:
    # Configs for platform alerts
    platform:
      email_configs:
        - smarthost: smtp.sendgrid.net:587
          from: <your-astronomer-alert-email@company.com>
          to: <your-email@company.com>
          auth_username: apikey
          auth_password: SG.myapikey1234567891234abcdef_bKY
          send_resolved: true
    platformCritical:
      slack_configs:
        - api_url: https://hooks.slack.com/services/abc12345/abcXYZ/xyz67890
          channel: '#<your-slack-channel-name>'
          text: |-
            {{ range .Alerts }}{{ .Annotations.description }}
            {{ end }}
          title: '{{ .CommonAnnotations.summary }}'
```
**Additional Notes:**

affects:

* https://docs.astronomer.io/software/platform-alerts
* https://docs.astronomer.io/software/0.27/platform-alerts
* https://docs.astronomer.io/software/0.26/platform-alerts/
* https://docs.astronomer.io/software/0.25/platform-alerts/
* https://docs.astronomer.io/software/0.25/platform-alerts/
* https://docs.astronomer.io/software/0.23/platform-alerts/
* https://docs.astronomer.io/software/0.16/platform-alerts/
